require 'colorize'
a = 1

while a == 1 do
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '0000000000000000'.blue
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '      0000000000000000'.blue
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '            0000000000000000'.blue
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '      0000000000000000'.blue
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '        0    '.red
puts '0000000000000000'.blue
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '        0     '.green
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '              0    '.red
puts '      0000000000000000'.blue
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '              0     '.green
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '                    0    '.red
puts '            0000000000000000'.blue
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '                    0     '.green
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                        0    '.red
puts '                0000000000000000'.blue
puts '                        0     '.green
puts '                        0     '.green
puts '                        0     '.green
puts '                        0     '.green
puts '                        0     '.green
end
